#! /bin/bash

# exit on any command raising an error
set -e

# exit the container if we don't need it on this machine
if [ ! ${START_CONTAINER} -eq 1 ]; then
    exit 0
fi

# wait indefinitely if we want to inspect the container without running sync
if [ ! ${RUN_SYNC} -eq 1 ]; then
    tail -f /dev/null
fi

if ! [ -d /mnt/sync ]; then
    echo "Error: external hard drive was not mounted correctly."
    echo "Note that it needs to be formatted as exFAT and called resilio-db."
    exit 1
fi

mkdir -p /mnt/sync/folders
mkdir -p /mnt/sync/config

if ! [ -f /mnt/sync/sync.conf ]; then
    cp /etc/sync.conf.default /mnt/sync/sync.conf;
fi

HOME=/mnt/sync/folders exec /usr/bin/rslsync --nodaemon $*
